[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# Run probe-rs for flashing the executable on the board.
runner = "probe-rs run --chip RP235x"

rustflags = [
  "-C", "linker=flip-link",
  "-C", "link-arg=--nmagic",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tlink-rp.x",
  "-C", "link-arg=-Tdefmt.x",

  # Code-size optimizations.
  #   trap unreachable can save a lot of space, but requires nightly compiler.
  #   uncomment the next line if you wish to enable it
  # "-Z", "trap-unreachable=no",
  # "-C", "inline-threshold=5",  # deprecated
  "-C", "no-vectorize-loops",
]

[build]
target = "thumbv8m.main-none-eabihf"

[env]
DEFMT_LOG = "debug"
